### ISSUE TITLE
Display Rotation

### ISSUE THREAD

**Issue by belangerpascal** [sassanh/headless-kivy#12]
Hi, would it be possible to add the capability if rotating the display?
And also setting offsets, I'm using a 1.69 Waveshare display with rounded corners with a resolution of 280x240.

Thanks

**Comment by mehrdadfeller** [comment]
@belangerpascal we don't have access to that specific display at the moment. have you tried running the current implementation on your display? if so, does it work on your display other than the resolution and size difference?

**Comment by belangerpascal** [comment]
It is working if I specify a width of 240 and a height of 240. If I put the displays 280x240 resolution, it's displays garbage.

**Comment by belangerpascal** [comment]
I did try to modify the Adafruit board setup in the config.py by changing the offset and adding rotate=90 but why I execute the code it doesn't seem to pick it up.

**Comment by belangerpascal** [comment]
This is with the native resolution (280x240)
![IMG_5440](https://github.com/ubopod/headless-kivy-pi/assets/54826336/36db8de8-bf0a-4b27-a9ad-f415e92fa136)

This is with a resolution of 240x240
![IMG_5441](https://github.com/ubopod/headless-kivy-pi/assets/54826336/af07b3ec-aaef-4862-9c9b-7e0bd2d474e5)

**Comment by sassanh** [comment]
@belangerpascal
I think it's a good idea to add rotation as a config parameter, I will work on it quickly.
I guess you have already tried both 280x240 and 240x280 and none are working, so assuming your `HeadlessWidget`'s name is `headless_widget`, please let me know what is the value of `headless_widget.size` and `headless_widget.pos`. Is it the root widget of the application?

**Comment by belangerpascal** [comment]
Thanks for that. Yes I did try playing with swapping the width and height and it shows all noise if I go higher then 240.

I do not specifically set the widget size or position.

**Comment by sassanh** [comment]
> I do not specifically set the widget size or position.

I see, even if you are not specifying the pos and size, Kivy may set them by itself if the headless widget is not the root widget. I suggest printing those values and check them, you can do it like this:

```python
print(widget.pos, widget.size)
```

Another troubleshooting step would be to run your application with `HEADLESS_KIVY_PI_DEBUG` environment variable set to `True` like this:

```bash
HEADLESS_KIVY_PI_DEBUG=True python /path/of/your/app
```

In this mode it will write the raw display data in a file named `headless_kivy_pi_buffer.raw`, if you share that file here I will be able to investigate the issue.

The output of this snippet would be helpful too:
```python
import headless_kivy_pi.config
print headless_kivy_pi.config._config
```
