### ISSUE TITLE
Custom display driver with Raspberry PI

### ISSUE THREAD

**Issue by hishizuka** [sassanh/headless-kivy#13]
Hi, 

I have released a program in PyQt and QML that transfers the drawing buffer to the SPI display in the same way as your program.
https://github.com/hishizuka/pizero_bikecomputer

I wanted to do the same thing in Kivy, but my hands had been tied for several years. I am very impressed with your program.
My project is similar to yours (Ubo) in that I am building a device that lets the various hardware of the Raspberry Pi do the work and control it through displays and buttons. 

I would love to use your program in my project. Is the following request possible?

- I want to use Fake() on Raspberry Pi instead of adafruit_st7789.
- After getting `data`( = np.frombuffer(self.texture.pixels, dtype=np.uint8  in `render_on_display` of `__init__.py`), I want to connect to any callback function instead of going to downstream processing.

**Comment by sassanh** [comment]
Hi,

I think these are good ideas to make this project more accessible and customizable.

Would it work for you if we do these things?
1. Drop the hardcoded condition of `if IS_RPI` for faking and let an environment variable/config parameter control it instead.
2. Replace the line that creates a thread for running `transfer_to_display`, with a callback provided in the config.

This way, headless-kivy would still generate hashes of frames and manage the fps and only the final rendering on the real display would be delegated to the callback. You can still disable all the fps management logic by setting `HEADLESS_KIVY_PI_AUTOMATIC_FPS=False`.

**Comment by sassanh** [comment]
@hishizuka Please check if the latest version works for you.

Note that the name of the project has been renamed from `headless-kivy-pi` to `headless-kivy`. Since very few people are using it, I didn't create a migration notice in the previous pypi page.

https://github.com/sassanh/headless-kivy/releases/tag/v0.9.0

**Comment by hishizuka** [comment]
Hi, @sassanh 

Thanks for your update so much! I have tried with the new code.
I want to output to a 400x240 display, but when I change the WIDTH, it sometimes fails at line 254 of `__init__.py`.
I can get around this by adding `try` statement.

```
import numpy as np
from PIL import Image 

from threading import Thread
from numpy._typing import NDArray

import kivy

WIDTH = 400
HEIGHT = 240


def render(
    *,
    rectangle: tuple[int, int, int, int],
    data: NDArray[np.uint16],
    data_hash: int,
    last_render_thread: Thread,
) -> None:
    im = Image.fromarray(data.astype('uint8').reshape((HEIGHT, WIDTH, -1)))
    im.save("tmp.png")


from headless_kivy import config, HeadlessWidget
config.setup_headless_kivy({
    'callback': render,
    'width': WIDTH,
    'height': HEIGHT,
    'flip_vertical': True
})

from kivy.app import App
from kivy.uix.label import Label
from kivy.uix.gridlayout import GridLayout


class FboGridLayout(GridLayout, HeadlessWidget):
    def __init__(self, **kwargs):
        super(FboGridLayout, self).__init__(**kwargs)

class MyApp(App):
    def build(self):
        fbg = FboGridLayout(rows=2, cols=2)
        fbg.add_widget(Label(text='Hello 1'))
        fbg.add_widget(Label(text='Hello 2'))
        fbg.add_widget(Label(text='Hello 3'))
        fbg.add_widget(Label(text='Hello 4'))
        return fbg


if __name__ == '__main__':
    MyApp().run()
```

File "/home/pi/code/headless-kivy/headless_kivy/__init__.py", line 254, in render_on_display
     HeadlessWidget.raw_data[self.x : self.x + self.width][
 ValueError: could not broadcast input array from shape (400,240,3) into shape (240,240,3)

**Comment by hishizuka** [comment]
Also, you define data as `uint16`, but are you dealing with more than 65536 colors? I thought `uint8` would be more appropriate for the #RRGGBB format.

`__init__.py` L247
```
data = data.reshape(self.width, self.height, -1)[:, :, :3].astype(np.uint16)
```

**Comment by sassanh** [comment]
@hishizuka Thank you so much for providing the reproduction code. I created a `demo.py` file in the repository based on your code, assuming I had your permission.

> File "/home/pi/code/headless-kivy/headless_kivy/**init**.py", line 254, in render_on_display
> HeadlessWidget.raw_data[self.x : self.x + self.width][
> ValueError: could not broadcast input array from shape (400,240,3) into shape (240,240,3)

Since we were solely using this code with a square display, we hadn't noticed this issue and couldn't reproduce #12. Thanks to your reproduction code, I could now work on it.

> Also, you define data as `uint16`

Good point! We needed `uint16` for Ubo code. I converted the rest to `uint8` in headless-kivy, I will migrate it back to `uint16` in ubo-app.

Please check the latest version 0.9.3 and see if it works. I also added alpha channel as you can see in the demo, so you may need to drop it based on your use-case.

**Comment by hishizuka** [comment]
Hi, @sassanh 

Thanks for the update. It worked here too.

This is an unrelated request, but the version of kivy that comes in with apt install in Bookworm is 2.1.0.
Is it possible to allow the user to specify line 30 of `config.py`?

```
kivy.require('2.3.0')
```

**Comment by sassanh** [comment]
@hishizuka If you are sure it works with 2.1.0 without any issues I can drop the required version to 2.1.0.

**Comment by hishizuka** [comment]
HI, @sassanh 

At least the original code in demo.py that I put in this issue worked fine in 2.1.0.
It will take some time, but I plan to incorporate it into my own project. I will let you know if there are any problems at that time.

**Comment by sassanh** [comment]
Done in [version 0.9.5](https://github.com/sassanh/headless-kivy/releases/tag/v0.9.5)
